# Generated by Django 2.1.1 on 2018-12-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_transito', '0002_reportetransito_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportetransito',
            name='latitud',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='reportetransito',
            name='longitud',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
    ]
